env:
  es6: true
  node: true
  browser: false
  mocha: true
extends: 'eslint:recommended'
globals:
  should: true
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  strict:
    - error
    - global
  no-console:
    - off
  max-len: [1, 100, 4]